### PR TITLE
Remove RDN specific link colors and styles

### PR DESCRIPTION
**Pull request by alex-deaconu**
I basically removed link color/styles so common-style link colors are used.

`rdn-GridHeader` color was removed because it was inconsistent with the rest of the colors; header will now be black instead of blue. Should not make much of a difference as the header names are not clickable in the first place.

Staged at http://1-09-004.rvauser2.appspot.com/

@RV-Adrian please review. @ezequielc @fjvallarino FYI. Thanks!

### CODE REVIEW

**Comment by fjvallarino** [comment]
@alex-deaconu I don't see/understand the difference in the header color when comparing to production.

Beyond that :+1:

**Comment by alex-deaconu** [comment]
@fjvallarino header style difference can be seen in the Schedule Items list for example: https://screencast.com/t/3RFbJ3Fp. Thanks

**Comment by fjvallarino** [comment]
@alex-deaconu looks good

:+1:

**Comment by RV-Adrian** [comment]
@alex-deaconu 👍 all good

**Pull request merged**
