### PR TITLE
Extend deprecation to May 31

### PR DESCRIPTION
**Pull request by alex-deaconu**
Staged at http://1-12-007.rvauser2.appspot.com/

@Rise-Vision/apps please review. Thanks!

### CODE REVIEW

**Comment by fjvallarino** [comment]
@alex-deaconu just to be sure: does this mean the Classic Editor (RVA) is disabled? Will this article be updated too (it still mentions Nov 2018)? https://help.risevision.com/hc/en-us/community/posts/360011541143-Classic-Editor-rva-risevision-com-End-of-life

**Comment by alex-deaconu** [comment]
@fjvallarino I'm not sure what the deprecation will involve... As for updating the article, it is part of the card for this. Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu mainly wondering if the year should be 2019 instead of 2018 (since the commit mentions "Extending deprecation..."

**Comment by alex-deaconu** [comment]
@fjvallarino oops, definitely! Missed that, good catch.

**Comment by fjvallarino** [comment]
@alex-deaconu looks good 👍

**Pull request merged**
